name: Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r agenda_contatos/requirements.txt

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Run tests
        working-directory: ./agenda_contatos
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=agenda_contatos --cov-report=xml --cov-report=term -v

      - name: Upload converage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          # directory: ./agenda_contatos

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Deploy to production server
  #       run: |
  #         echo "Deploying to production server..."
  #         # Add your deployment commands here
