
CREATE TABLE IF NOT EXISTS Empresa (
	id INT NOT NULL,
	Empresa VARCHAR(40) NULL DEFAULT NULL,
	PRIMARY KEY (id)
);


INSERT INTO Empresa (id, Empresa) VALUES
	(1, 'ALTA MARÉ SERVICOS LTDA'),
	(2, 'DESTRA PRESTADORA DE SERVIÇOS LTDA'),
	(3, 'DEFENSE SEGURANÇA ELETRÔNICA'),
	(4, 'CUSTOM SERVICE LTDA');

